---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-rbd
   namespace: storage
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: afb1a3b4-bcf7-4eb8-bf8c-96fb7da55847
   pool: se-jar-k8sdeploy01
   volumeNamePrefix: "se-jar-k8sdeploy01-"
   imageFeatures: layering
   csi.storage.k8s.io/fstype: ext4
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: storage
   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: storage
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: storage
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
   - discard
